# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Python

on:
  pull_request:
  push:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    env:
      SDIST_DIR: /tmp/sdist
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ".[dev]"
    - name: Test with pytest
      run: |
        python -m pytest
        codecov
    - name: Build and validate
      run: |
        python -m build --wheel
        python -m build --sdist --outdir ${SDIST_DIR}/
        twine check ${SDIST_DIR}/*
        check-manifest -p python ${PWD}
        cd ${SDIST_DIR}
        pip install $(ls ${SDIST_DIR})
